### ISSUE TITLE
layout do frontend

### ISSUE THREAD

**Issue by ivandinizaj** [uninassau-2020-2/sidi-grupo2#4]
Aqui será discutido sobre o layout desde o `wireframe` ao `layout final`.

**Comment by eikeathylas** [comment]
![Layout](https://user-images.githubusercontent.com/47196367/94386795-d76fb100-011e-11eb-8eb8-c063c185202b.jpeg)

**Comment by hubity** [comment]
**Layout search CEP**

![Web 1920 – 1](https://user-images.githubusercontent.com/43327416/94473189-3f1b1000-01a2-11eb-9c1f-d38172b7a56f.png)

**Comment by hubity** [comment]
https://xd.adobe.com/view/b61a6578-5783-409d-9245-28f938ca35f1-e349/
